const path=require('path');const http=require('http');const crypto=require('crypto');const express=require('express');const cors=require('cors');const {Server}=require('socket.io');const jwt=require('jsonwebtoken');const {Pool}=require('pg');
require('dotenv').config({path:path.join(__dirname,'../.env')});
const app=express();const server=http.createServer(app);const io=new Server(server,{cors:{origin:true,credentials:true}});
app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'../frontend')));
const PORT=process.env.PORT||3000, JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_DEV_ONLY';
const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgres://postgres:postgres@localhost:5432/manoraksha',ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:false});
const q=(text,params)=>pool.query(text,params);
function tokenFor(u){return jwt.sign({id:u.id,role:u.role},JWT_SECRET,{expiresIn:'8h'})}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid or expired session'})}}
const roles={victim:['/victim.html'],counsellor:['/counsellor.html'],district:['/district.html'],state:['/state.html'],national:['/national.html'],admin:['/admin.html']};
app.get('/health',async(req,res)=>{try{await q('SELECT 1');res.json({status:'ok',service:'manoraksha-api',time:new Date().toISOString()})}catch(e){res.status(503).json({status:'database_unavailable'})}});
app.post('/api/auth/demo-login',async(req,res)=>{const {email,role='victim'}=req.body;if(!email||!roles[role])return res.status(400).json({error:'Email and valid role are required'});let r=await q('SELECT * FROM users WHERE email=$1',[email]);let u=r.rows[0];if(!u){r=await q(`INSERT INTO users(email,display_name,role,language) VALUES($1,$2,$3,$4) RETURNING *`,[email,email.split('@')[0],role,'English']);u=r.rows[0]}else if(u.role!==role){return res.status(403).json({error:'This demo account has another role'})}res.json({token:tokenFor(u),redirect:roles[role][0]})});
app.get('/api/auth/me',auth,async(req,res)=>{const r=await q('SELECT id,email,display_name,role,language,status FROM users WHERE id=$1',[req.user.id]);if(!r.rows[0])return res.status(404).json({error:'User not found'});res.json({user:r.rows[0]})});
app.get('/api/privacy',auth,async(req,res)=>{let r=await q('SELECT * FROM consents WHERE user_id=$1',[req.user.id]);if(!r.rows[0])const r=await q(`INSERT INTO consents(user_id) VALUES($1) RETURNING *`,[req.user.id]);res.json(r.rows[0])});
app.put('/api/privacy',auth,async(req,res)=>{const b=req.body;const r=await q(`INSERT INTO consents(user_id,analytics,voice,longitudinal,counsellor_access,privacy_locked) VALUES($1,$2,$3,$4,$5,false) ON CONFLICT(user_id) DO UPDATE SET analytics=EXCLUDED.analytics,voice=EXCLUDED.voice,longitudinal=EXCLUDED.longitudinal,counsellor_access=EXCLUDED.counsellor_access,updated_at=now() RETURNING *`,[req.user.id,!!b.analytics,!!b.voice,!!b.longitudinal,!!b.counsellor_access]);res.json(r.rows[0])});
app.post('/api/privacy/lock',auth,async(req,res)=>{const const r=await q(`INSERT INTO consents(user_id,analytics,voice,longitudinal,counsellor_access,privacy_locked) VALUES($1,false,false,false,false,true) ON CONFLICT(user_id) DO UPDATE SET analytics=false,voice=false,longitudinal=false,counsellor_access=false,privacy_locked=true,updated_at=now() RETURNING *`,[req.user.id]);res.json(r.rows[0])});
app.post('/api/checkins',auth,async(req,res)=>{if(req.user.role!=='victim')return res.status(403).json({error:'Only beneficiaries can submit check-ins'});const b=req.body;if(!Number.isInteger(+b.mood)||!Number.isInteger(+b.anxiety)||!Number.isInteger(+b.sleep_difficulty))return res.status(400).json({error:'Invalid check-in scores'});let cr=await q('SELECT id FROM cases WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.user.id]);if(!cr.rows[0])cr=await q(`INSERT INTO cases(user_id,status) VALUES($1,'active') RETURNING id`,[req.user.id]);const ai=await (await fetch((process.env.AI_URL||'http://localhost:8000')+'/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mood:+b.mood,anxiety:+b.anxiety,sleep_difficulty:+b.sleep_difficulty,feels_unsafe:!!b.feels_unsafe,message:b.message||'',language:b.language||'English'})})).json().catch(()=>({level:'unknown',explanation:'AI service unavailable; human review required.',score:null}));const r=await q(`INSERT INTO checkins(case_id,language,mood,anxiety,sleep_difficulty,feels_unsafe,message) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,created_at`,[cr.rows[0].id,b.language||'English',+b.mood,+b.anxiety,+b.sleep_difficulty,!!b.feels_unsafe,b.message||'']);await q(`INSERT INTO risk_events(case_id,level,score,signals,explanation) VALUES($1,$2,$3,$4,$5)`,[cr.rows[0].id,ai.level,ai.score,JSON.stringify(ai.signals||[]),ai.explanation]);io.emit('risk.updated',{caseId:cr.rows[0].id,level:ai.level});res.json({checkin:r.rows[0],ai})});
app.post('/api/emergency',auth,async(req,res)=>{let cr=await q('SELECT id FROM cases WHERE user_id=$1 ORDER BY created_at DESC LIMIT 1',[req.user.id]);if(!cr.rows[0])cr=await q(`INSERT INTO cases(user_id,status) VALUES($1,'active') RETURNING id`,[req.user.id]);const r=await q(`INSERT INTO emergency_events(case_id,reason) VALUES($1,$2) RETURNING *`,[cr.rows[0].id,String(req.body.reason||'Immediate support requested').slice(0,1000)]);io.emit('emergency.created',{id:r.rows[0].id,caseId:cr.rows[0].id});await q(`INSERT INTO audit_logs(actor_user_id,action,resource_type,resource_id) VALUES($1,'emergency_created','emergency_event',$2)`,[req.user.id,r.rows[0].id]);res.status(201).json(r.rows[0])});
app.get('/api/dashboard/overview',auth,async(req,res)=>{if(req.user.role==='victim')return res.status(403).json({error:'Dashboard unavailable'});const [a,b,c,d,e]=await Promise.all([q('SELECT count(*)::int n FROM cases'),q(`SELECT count(*)::int n FROM risk_events WHERE level='urgent'`),q(`SELECT count(*)::int n FROM risk_events WHERE level='elevated'`),q(`SELECT count(*)::int n FROM emergency_events WHERE status='unacknowledged'`),q(`SELECT level,count(*)::int n FROM risk_events GROUP BY level`)]);const cases=await q(`SELECT c.id case_id,COALESCE(re.level,'unknown') level,c.status,c.created_at FROM cases c LEFT JOIN LATERAL (SELECT level FROM risk_events WHERE case_id=c.id ORDER BY created_at DESC LIMIT 1) re ON true ORDER BY c.created_at DESC LIMIT 30`);const events=await q(`SELECT 'emergency' type,created_at FROM emergency_events UNION ALL SELECT 'risk' type,created_at FROM risk_events ORDER BY created_at DESC LIMIT 20`);res.json({totalCases:a.rows[0].n,urgent:b.rows[0].n,elevated:c.rows[0].n,pending:d.rows[0].n,risk:Object.fromEntries(e.rows.map(x=>[x.level,x.n])),cases:cases.rows,events:events.rows})});
io.use((socket,next)=>{try{socket.user=jwt.verify(socket.handshake.auth?.token||'',JWT_SECRET);next()}catch(e){next(new Error('Unauthorized'))}});
io.on('connection',socket=>{socket.join('role:'+socket.user.role);socket.on('disconnect',()=>{})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../frontend/index.html')));
server.listen(PORT,()=>console.log(`ManoRaksha API listening on ${PORT}`));